package com.example.myapplication.ui.ddlwithsearch

val countryList = listOf(
    Country("AF", "Afeganistão", "AFG"),
    Country("ZA", "África do Sul", "ZAF"),
    Country("AL", "Albânia", "ALB"),
    Country("DE", "Alemanha", "DEU"),
    Country("AD", "Andorra", "AND"),
    Country("AO", "Angola", "AGO"),
    Country("AI", "Anguilla", "AIA"),
    Country("AQ", "Antártica", "ATA"),
    Country("AG", "Antígua e Barbuda", "ATG"),
    Country("SA", "Arábia Saudita", "SAU"),
    Country("DZ", "Argélia", "DZA"),
    Country("AR", "Argentina", "ARG"),
    Country("AM", "Armênia", "ARM"),
    Country("AW", "Aruba", "ABW"),
    Country("AU", "Austrália", "AUS"),
    Country("AT", "Áustria", "AUT"),
    Country("AZ", "Azerbaijão", "AZE"),
    Country("BS", "Bahamas", "BHS"),
    Country("BH", "Bahrein", "BHR"),
    Country("BD", "Bangladesh", "BGD"),
    Country("BB", "Barbados", "BRB"),
    Country("BE", "Bélgica", "BEL"),
    Country("BZ", "Belize", "BLZ"),
    Country("BJ", "Benim", "BEN"),
    Country("BM", "Bermudas", "BMU"),
    Country("BY", "Bielorrússia", "BLR"),
    Country("BO", "Bolívia", "BOL"),
    Country("BA", "Bósnia e Herzegovina", "BIH"),
    Country("BW", "Botswana", "BWA"),
    Country("BR", "Brasil", "BRA"),
    Country("BN", "Brunei", "BRN"),
    Country("BG", "Bulgária", "BGR"),
    Country("BF", "Burkina Faso", "BFA"),
    Country("BI", "Burundi", "BDI"),
    Country("BT", "Butão", "BTN"),
    Country("CV", "Cabo Verde", "CPV"),
    Country("CM", "Camarões", "CMR"),
    Country("KH", "Camboja", "KHM"),
    Country("CA", "Canadá", "CAN"),
    Country("QA", "Catar", "QAT"),
    Country("CL", "Chile", "CHL"),
    Country("CN", "China", "CHN"),
    Country("CY", "Chipre", "CYP"),
    Country("CO", "Colômbia", "COL"),
    Country("KM", "Comores", "COM"),
    Country("CG", "Congo", "COG"),
    Country("KR", "Coreia do Sul", "KOR"),
    Country("KP", "Coreia do Norte", "PRK"),
    Country("CI", "Costa do Marfim", "CIV"),
    Country("CR", "Costa Rica", "CRI"),
    Country("HR", "Croácia", "HRV"),
    Country("CU", "Cuba", "CUB"),
    Country("DK", "Dinamarca", "DNK"),
    Country("DJ", "Djibouti", "DJI"),
    Country("DM", "Dominica", "DMA"),
    Country("EG", "Egito", "EGY"),
    Country("SV", "El Salvador", "SLV"),
    Country("AE", "Emirados Árabes Unidos", "ARE"),
    Country("EC", "Equador", "ECU"),
    Country("ER", "Eritreia", "ERI"),
    Country("SK", "Eslováquia", "SVK"),
    Country("SI", "Eslovênia", "SVN"),
    Country("ES", "Espanha", "ESP"),
    Country("US", "Estados Unidos", "USA"),
    Country("EE", "Estônia", "EST"),
    Country("ET", "Etiópia", "ETH"),
    Country("FJ", "Fiji", "FJI"),
    Country("PH", "Filipinas", "PHL"),
    Country("FI", "Finlândia", "FIN"),
    Country("FR", "França", "FRA"),
    Country("GA", "Gabão", "GAB"),
    Country("GM", "Gâmbia", "GMB"),
    Country("GH", "Gana", "GHA"),
    Country("GE", "Geórgia", "GEO"),
    Country("GI", "Gibraltar", "GIB"),
    Country("GR", "Grécia", "GRC"),
    Country("GD", "Granada", "GRD"),
    Country("GL", "Groenlândia", "GRL"),
    Country("GP", "Guadalupe", "GLP"),
    Country("GU", "Guam", "GUM"),
    Country("GT", "Guatemala", "GTM"),
    Country("GY", "Guiana", "GUY"),
    Country("GF", "Guiana Francesa", "GUF"),
    Country("GN", "Guiné", "GIN"),
    Country("GW", "Guiné-Bissau", "GNB"),
    Country("GQ", "Guiné Equatorial", "GNQ"),
    Country("HT", "Haiti", "HTI"),
    Country("NL", "Holanda", "NLD"),
    Country("HN", "Honduras", "HND"),
    Country("HU", "Hungria", "HUN"),
    Country("YE", "Iêmen", "YEM"),
    Country("IN", "Índia", "IND"),
    Country("ID", "Indonésia", "IDN"),
    Country("IR", "Irã", "IRN"),
    Country("IQ", "Iraque", "IRQ"),
    Country("IE", "Irlanda", "IRL"),
    Country("IS", "Islândia", "ISL"),
    Country("IL", "Israel", "ISR"),
    Country("IT", "Itália", "ITA"),
    Country("JM", "Jamaica", "JAM"),
    Country("JP", "Japão", "JPN"),
    Country("JO", "Jordânia", "JOR"),
    Country("KW", "Kuwait", "KWT"),
    Country("LA", "Laos", "LAO"),
    Country("LV", "Letônia", "LVA"),
    Country("LB", "Líbano", "LBN"),
    Country("LR", "Libéria", "LBR"),
    Country("LY", "Líbia", "LBY"),
    Country("LI", "Liechtenstein", "LIE"),
    Country("LT", "Lituânia", "LTU"),
    Country("LU", "Luxemburgo", "LUX"),
    Country("MK", "Macedônia do Norte", "MKD"),
    Country("MG", "Madagascar", "MDG"),
    Country("MY", "Malásia", "MYS"),
    Country("MW", "Malawi", "MWI"),
    Country("MV", "Maldivas", "MDV"),
    Country("ML", "Mali", "MLI"),
    Country("MT", "Malta", "MLT"),
    Country("MA", "Marrocos", "MAR"),
    Country("MU", "Maurício", "MUS"),
    Country("MR", "Mauritânia", "MRT"),
    Country("MX", "México", "MEX"),
    Country("MZ", "Moçambique", "MOZ"),
    Country("MD", "Moldávia", "MDA"),
    Country("MC", "Mônaco", "MCO"),
    Country("MN", "Mongólia", "MNG"),
    Country("ME", "Montenegro", "MNE"),
    Country("NA", "Namíbia", "NAM"),
    Country("NP", "Nepal", "NPL"),
    Country("NI", "Nicarágua", "NIC"),
    Country("NE", "Níger", "NER"),
    Country("NG", "Nigéria", "NGA"),
    Country("NO", "Noruega", "NOR"),
    Country("NZ", "Nova Zelândia", "NZL"),
    Country("OM", "Omã", "OMN"),
    Country("PA", "Panamá", "PAN"),
    Country("PG", "Papua-Nova Guiné", "PNG"),
    Country("PK", "Paquistão", "PAK"),
    Country("PY", "Paraguai", "PRY"),
    Country("PE", "Peru", "PER"),
    Country("PL", "Polônia", "POL"),
    Country("PT", "Portugal", "PRT"),
    Country("KE", "Quênia", "KEN"),
    Country("GB", "Reino Unido", "GBR"),
    Country("CF", "República Centro-Africana", "CAF"),
    Country("CZ", "República Tcheca", "CZE"),
    Country("DO", "República Dominicana", "DOM"),
    Country("RO", "Romênia", "ROU"),
    Country("RW", "Ruanda", "RWA"),
    Country("RU", "Rússia", "RUS"),
    Country("EH", "Saara Ocidental", "ESH"),
    Country("WS", "Samoa", "WSM"),
    Country("SM", "San Marino", "SMR"),
    Country("LC", "Santa Lúcia", "LCA"),
    Country("VC", "São Vicente e Granadinas", "VCT"),
    Country("ST", "São Tomé e Príncipe", "STP"),
    Country("SN", "Senegal", "SEN"),
    Country("RS", "Sérvia", "SRB"),
    Country("SC", "Seychelles", "SYC"),
    Country("SG", "Singapura", "SGP"),
    Country("SY", "Síria", "SYR"),
    Country("SO", "Somália", "SOM"),
    Country("LK", "Sri Lanka", "LKA"),
    Country("SD", "Sudão", "SDN"),
    Country("SS", "Sudão do Sul", "SSD"),
    Country("SE", "Suécia", "SWE"),
    Country("CH", "Suíça", "CHE"),
    Country("SR", "Suriname", "SUR"),
    Country("TH", "Tailândia", "THA"),
    Country("TW", "Taiwan", "TWN"),
    Country("TZ", "Tanzânia", "TZA"),
    Country("TJ", "Tajiquistão", "TJK"),
    Country("TG", "Togo", "TGO"),
    Country("TT", "Trinidad e Tobago", "TTO"),
    Country("TN", "Tunísia", "TUN"),
    Country("TR", "Turquia", "TUR"),
    Country("UA", "Ucrânia", "UKR"),
    Country("UG", "Uganda", "UGA"),
    Country("UY", "Uruguai", "URY"),
    Country("UZ", "Uzbequistão", "UZB"),
    Country("VE", "Venezuela", "VEN"),
    Country("VN", "Vietnã", "VNM"),
    Country("ZM", "Zâmbia", "ZMB"),
    Country("ZW", "Zimbábue", "ZWE")
)